# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e7a9df4a77b7fc3034a650dc1e514b27e68cbaa7a52ade026439cf20057a7e4712151e23f55434ba37b889fdbc014a412af9ddb187564abd7c16d2135f6c9b0

test:
  secret_key_base: 4cbc2421cc9c476d320a25911101b2135a481b13df5f7f8961b6e2d9929f0942d3bee7fe556b755c07e78b9eda6d95a7a14f5491fe5d487ca15ae4820010ef40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
